/**
 * East Tunnels — 31 rooms.
 * Garrison manhole (G, int_1_4) lands at sewer_east_hub.
 * Heavy cathedral foundations, stone masonry.
 * Halls of the Dead crack (H) enters the lower-east section.
 * Warrens of Filth entrance (W) on the far east.
 * Level 4-5 mobs.
 */
import { DistrictData } from '../../arindale/types.js';
import { sewerDescription, maybeAddSewerDetail } from '../descriptions.js';

function desc(tag: string): string {
  return maybeAddSewerDetail(sewerDescription('east', tag), tag);
}

export function getEastTunnels(): DistrictData {
  return {
    rooms: [
      {
        tag: 'sewer_entrance_warrens',
        name: 'Vermin-Gnawed Opening',
        description: `The tunnel wall has been chewed and clawed through here, creating a ragged opening just large enough to crawl through. The edges of the hole are smooth with use, and the stench emanating from beyond is overwhelming — a concentrated reek of animal filth, matted fur, and rotting food. Faint squeaking and scratching sounds echo from the dark passage beyond.`,
        area: 'Arindale Sewer',
        terrain: 'underground',
        darkness_level: -120,
      },
      {
        tag: 'sewer_east_junction',
        name: 'Eastern Junction',
        description: `A junction where the main sewer line meets tunnels that run beneath the cathedral and garrison districts. The construction is heavy here — thick stone walls and a low vaulted ceiling that bears the weight of the city's most massive buildings. A cold draft pushes through from the south.`,
        area: 'Arindale Sewer',
        terrain: 'underground',
        darkness_level: -120,
      },
      {
        tag: 'sewer_east_hub',
        name: 'Sewer Tunnel',
        description: `A sturdy tunnel beneath the garrison district. The weight of the military buildings above is evident in the massive stone blocks that form the walls. A shaft of dim light falls from a heavy manhole cover overhead, barely illuminating the passage. The air is dry and cold.`,
        area: 'Arindale Sewer',
        terrain: 'underground',
        darkness_level: -120,
      },
      {
        tag: 'sewer_east_1',
        name: 'Deep Stone Tunnel',
        description: desc('sewer_east_1'),
        area: 'Arindale Sewer',
        terrain: 'underground',
        darkness_level: -120,
      },
      {
        tag: 'sewer_east_2',
        name: 'Foundation Tunnel',
        description: desc('sewer_east_2'),
        area: 'Arindale Sewer',
        terrain: 'underground',
        darkness_level: -120,
      },
      {
        tag: 'sewer_east_3',
        name: 'Stone Passage',
        description: desc('sewer_east_3'),
        area: 'Arindale Sewer',
        terrain: 'underground',
        darkness_level: -120,
      },
      {
        tag: 'sewer_east_4',
        name: 'Stone Corridor',
        description: desc('sewer_east_4'),
        area: 'Arindale Sewer',
        terrain: 'underground',
        darkness_level: -120,
      },
      {
        tag: 'sewer_east_5',
        name: 'Heavy Tunnel',
        description: desc('sewer_east_5'),
        area: 'Arindale Sewer',
        terrain: 'underground',
        darkness_level: -120,
      },
      {
        tag: 'sewer_east_6',
        name: 'Ancient Passage',
        description: desc('sewer_east_6'),
        area: 'Arindale Sewer',
        terrain: 'underground',
        darkness_level: -120,
      },
      {
        tag: 'sewer_east_7',
        name: 'Deep Stone Tunnel',
        description: desc('sewer_east_7'),
        area: 'Arindale Sewer',
        terrain: 'underground',
        darkness_level: -120,
      },
      {
        tag: 'sewer_east_8',
        name: 'Foundation Tunnel',
        description: desc('sewer_east_8'),
        area: 'Arindale Sewer',
        terrain: 'underground',
        darkness_level: -120,
      },
      {
        tag: 'sewer_east_9',
        name: 'Stone Passage',
        description: desc('sewer_east_9'),
        area: 'Arindale Sewer',
        terrain: 'underground',
        darkness_level: -120,
      },
      {
        tag: 'sewer_east_10',
        name: 'Stone Passage',
        description: desc('sewer_east_10'),
        area: 'Arindale Sewer',
        terrain: 'underground',
        darkness_level: -120,
      },
      {
        tag: 'sewer_east_11',
        name: 'Stone Corridor',
        description: desc('sewer_east_11'),
        area: 'Arindale Sewer',
        terrain: 'underground',
        darkness_level: -120,
      },
      {
        tag: 'sewer_east_12',
        name: 'Heavy Tunnel',
        description: desc('sewer_east_12'),
        area: 'Arindale Sewer',
        terrain: 'underground',
        darkness_level: -120,
      },
      {
        tag: 'sewer_east_13',
        name: 'Ancient Passage',
        description: desc('sewer_east_13'),
        area: 'Arindale Sewer',
        terrain: 'underground',
        darkness_level: -120,
      },
      {
        tag: 'sewer_east_14',
        name: 'Deep Stone Tunnel',
        description: desc('sewer_east_14'),
        area: 'Arindale Sewer',
        terrain: 'underground',
        darkness_level: -120,
      },
      {
        tag: 'sewer_east_15',
        name: 'Foundation Tunnel',
        description: desc('sewer_east_15'),
        area: 'Arindale Sewer',
        terrain: 'underground',
        darkness_level: -120,
      },
      {
        tag: 'sewer_east_16',
        name: 'Stone Passage',
        description: desc('sewer_east_16'),
        area: 'Arindale Sewer',
        terrain: 'underground',
        darkness_level: -120,
      },
      {
        tag: 'sewer_east_crack',
        name: 'Cracked Wall',
        description: `A jagged crack splits the tunnel wall here, running from floor to ceiling through ancient stonework. The gap is just wide enough for a person to squeeze through sideways. A cold, still breeze pushes through from the other side, carrying a faint otherworldly chill — the unmistakable breath of the dead. Faint pale light glows beyond the crack.`,
        area: 'Arindale Sewer',
        terrain: 'underground',
        darkness_level: -120,
      },
      {
        tag: 'sewer_east_17',
        name: 'Stone Corridor',
        description: desc('sewer_east_17'),
        area: 'Arindale Sewer',
        terrain: 'underground',
        darkness_level: -120,
      },
      {
        tag: 'sewer_east_18',
        name: 'Heavy Tunnel',
        description: desc('sewer_east_18'),
        area: 'Arindale Sewer',
        terrain: 'underground',
        darkness_level: -120,
      },
      {
        tag: 'sewer_east_19',
        name: 'Ancient Passage',
        description: desc('sewer_east_19'),
        area: 'Arindale Sewer',
        terrain: 'underground',
        darkness_level: -120,
      },
      {
        tag: 'sewer_east_20',
        name: 'Stone Corridor',
        description: desc('sewer_east_20'),
        area: 'Arindale Sewer',
        terrain: 'underground',
        darkness_level: -120,
      },
      {
        tag: 'sewer_east_21',
        name: 'Heavy Tunnel',
        description: desc('sewer_east_21'),
        area: 'Arindale Sewer',
        terrain: 'underground',
        darkness_level: -120,
      },
      {
        tag: 'sewer_east_22',
        name: 'Ancient Passage',
        description: desc('sewer_east_22'),
        area: 'Arindale Sewer',
        terrain: 'underground',
        darkness_level: -120,
      },
      {
        tag: 'sewer_east_23',
        name: 'Deep Stone Tunnel',
        description: desc('sewer_east_23'),
        area: 'Arindale Sewer',
        terrain: 'underground',
        darkness_level: -120,
      },
      {
        tag: 'sewer_east_24',
        name: 'Foundation Tunnel',
        description: desc('sewer_east_24'),
        area: 'Arindale Sewer',
        terrain: 'underground',
        darkness_level: -120,
      },
      {
        tag: 'sewer_east_25',
        name: 'Stone Passage',
        description: desc('sewer_east_25'),
        area: 'Arindale Sewer',
        terrain: 'underground',
        darkness_level: -120,
      },
      {
        tag: 'sewer_east_26',
        name: 'Stone Corridor',
        description: desc('sewer_east_26'),
        area: 'Arindale Sewer',
        terrain: 'underground',
        darkness_level: -120,
      },
      {
        tag: 'sewer_east_27',
        name: 'Heavy Tunnel',
        description: desc('sewer_east_27'),
        area: 'Arindale Sewer',
        terrain: 'underground',
        darkness_level: -120,
      },
    ],

    exits: [
      { fromTag: 'sewer_east_hub', toTag: 'int_1_4', direction: 'up' },
      { fromTag: 'int_1_4', toTag: 'sewer_east_hub', direction: 'down' },
      { fromTag: 'sewer_east_crack', toTag: 'cathedral_halls_dead', direction: 'east' },
      { fromTag: 'cathedral_halls_dead', toTag: 'sewer_east_crack', direction: 'west' },
      { fromTag: 'sewer_east_1', toTag: 'sewer_east_2', direction: 'east' },
      { fromTag: 'sewer_east_2', toTag: 'sewer_east_1', direction: 'west' },
      { fromTag: 'sewer_east_4', toTag: 'sewer_east_5', direction: 'east' },
      { fromTag: 'sewer_east_5', toTag: 'sewer_east_4', direction: 'west' },
      { fromTag: 'sewer_east_8', toTag: 'sewer_east_9', direction: 'east' },
      { fromTag: 'sewer_east_9', toTag: 'sewer_east_8', direction: 'west' },
      { fromTag: 'sewer_east_11', toTag: 'sewer_east_12', direction: 'east' },
      { fromTag: 'sewer_east_12', toTag: 'sewer_east_11', direction: 'west' },
      { fromTag: 'sewer_east_14', toTag: 'sewer_east_15', direction: 'east' },
      { fromTag: 'sewer_east_15', toTag: 'sewer_east_14', direction: 'west' },
      { fromTag: 'sewer_east_16', toTag: 'sewer_east_crack', direction: 'east' },
      { fromTag: 'sewer_east_crack', toTag: 'sewer_east_16', direction: 'west' },
      { fromTag: 'sewer_east_18', toTag: 'sewer_east_19', direction: 'east' },
      { fromTag: 'sewer_east_19', toTag: 'sewer_east_18', direction: 'west' },
      { fromTag: 'sewer_east_19', toTag: 'sewer_east_20', direction: 'east' },
      { fromTag: 'sewer_east_20', toTag: 'sewer_east_19', direction: 'west' },
      { fromTag: 'sewer_east_21', toTag: 'sewer_east_22', direction: 'east' },
      { fromTag: 'sewer_east_22', toTag: 'sewer_east_21', direction: 'west' },
      { fromTag: 'sewer_east_24', toTag: 'sewer_east_25', direction: 'east' },
      { fromTag: 'sewer_east_25', toTag: 'sewer_east_24', direction: 'west' },
      { fromTag: 'sewer_east_25', toTag: 'sewer_east_26', direction: 'east' },
      { fromTag: 'sewer_east_26', toTag: 'sewer_east_25', direction: 'west' },
      { fromTag: 'sewer_east_26', toTag: 'sewer_east_27', direction: 'east' },
      { fromTag: 'sewer_east_27', toTag: 'sewer_east_26', direction: 'west' },
      { fromTag: 'sewer_east_junction', toTag: 'sewer_east_2', direction: 'south' },
      { fromTag: 'sewer_east_2', toTag: 'sewer_east_junction', direction: 'north' },
      { fromTag: 'sewer_east_hub', toTag: 'sewer_east_3', direction: 'south' },
      { fromTag: 'sewer_east_3', toTag: 'sewer_east_hub', direction: 'north' },
      { fromTag: 'sewer_east_1', toTag: 'sewer_east_7', direction: 'south' },
      { fromTag: 'sewer_east_7', toTag: 'sewer_east_1', direction: 'north' },
      { fromTag: 'sewer_east_3', toTag: 'sewer_east_9', direction: 'south' },
      { fromTag: 'sewer_east_9', toTag: 'sewer_east_3', direction: 'north' },
      { fromTag: 'sewer_east_4', toTag: 'sewer_east_10', direction: 'south' },
      { fromTag: 'sewer_east_10', toTag: 'sewer_east_4', direction: 'north' },
      { fromTag: 'sewer_east_6', toTag: 'sewer_east_12', direction: 'south' },
      { fromTag: 'sewer_east_12', toTag: 'sewer_east_6', direction: 'north' },
      { fromTag: 'sewer_east_7', toTag: 'sewer_east_13', direction: 'south' },
      { fromTag: 'sewer_east_13', toTag: 'sewer_east_7', direction: 'north' },
      { fromTag: 'sewer_east_8', toTag: 'sewer_east_15', direction: 'south' },
      { fromTag: 'sewer_east_15', toTag: 'sewer_east_8', direction: 'north' },
      { fromTag: 'sewer_east_10', toTag: 'sewer_east_crack', direction: 'south' },
      { fromTag: 'sewer_east_crack', toTag: 'sewer_east_10', direction: 'north' },
      { fromTag: 'sewer_east_11', toTag: 'sewer_east_17', direction: 'south' },
      { fromTag: 'sewer_east_17', toTag: 'sewer_east_11', direction: 'north' },
      { fromTag: 'sewer_east_13', toTag: 'sewer_east_18', direction: 'south' },
      { fromTag: 'sewer_east_18', toTag: 'sewer_east_13', direction: 'north' },
      { fromTag: 'sewer_east_14', toTag: 'sewer_east_19', direction: 'south' },
      { fromTag: 'sewer_east_19', toTag: 'sewer_east_14', direction: 'north' },
      { fromTag: 'sewer_east_16', toTag: 'sewer_east_21', direction: 'south' },
      { fromTag: 'sewer_east_21', toTag: 'sewer_east_16', direction: 'north' },
      { fromTag: 'sewer_east_17', toTag: 'sewer_east_23', direction: 'south' },
      { fromTag: 'sewer_east_23', toTag: 'sewer_east_17', direction: 'north' },
      { fromTag: 'sewer_east_20', toTag: 'sewer_east_24', direction: 'south' },
      { fromTag: 'sewer_east_24', toTag: 'sewer_east_20', direction: 'north' },
      { fromTag: 'sewer_east_21', toTag: 'sewer_east_25', direction: 'south' },
      { fromTag: 'sewer_east_25', toTag: 'sewer_east_21', direction: 'north' },
      { fromTag: 'sewer_east_23', toTag: 'sewer_east_27', direction: 'south' },
      { fromTag: 'sewer_east_27', toTag: 'sewer_east_23', direction: 'north' },
    ],

    doors: [
      {
        name: 'manhole',
        doorType: 'triggered_passageway',
        entryTag: 'int_1_4',
        entryDirection: 'down',
        defaultState: 'closed',
        autoResetSeconds: 30,
        isHidden: true,
        triggerText: 'go manhole',
        passageMessageSelf: 'You lift the heavy iron grate and climb down into the sewer.',
        passageMessageRoom: '{player} lifts a manhole grate and climbs down into the darkness below.',
      },
      {
        name: 'crack in the wall',
        doorType: 'triggered_passageway',
        entryTag: 'cathedral_halls_dead',
        entryDirection: 'west',
        exitTag: 'sewer_east_crack',
        exitDirection: 'east',
        defaultState: 'open',
        autoResetSeconds: 0,
        isHidden: true,
        triggerText: 'go crack',
        passageMessageSelf: 'You squeeze through the narrow crack in the wall, scraping against rough stone.',
        passageMessageRoom: '{player} squeezes through a narrow crack in the wall and disappears.',
      }
    ],
  };
}
