/**
 * North Tunnels — 85 rooms.
 * Harbor manhole (K, int_0_2) lands at sewer_north_hub.
 * Drain Outflow (D) at the far north — future connection outside walls.
 * Sanctum of the Damned entrance (S) in the upper-east.
 * Flooded Section (F) in the northwest — quest area.
 * Damp, waterfront seepage, brine and tide debris.
 * Level 3-4 mobs.
 */
import { DistrictData } from '../../arindale/types.js';
import { sewerDescription, maybeAddSewerDetail } from '../descriptions.js';

function desc(tag: string): string {
  return maybeAddSewerDetail(sewerDescription('north', tag), tag);
}

function flDesc(tag: string): string {
  return maybeAddSewerDetail(sewerDescription('flooded', tag), tag);
}
export function getNorthTunnels(): DistrictData {
  return {
    rooms: [
      {
        tag: 'sewer_drain_outflow',
        name: 'Drain Outflow',
        description: `The tunnel reaches its northern terminus near the city's harbor-side foundations. A heavy iron grate is set into a thick stone wall, beyond which a drainage channel slopes downward toward the waterfront. The faint sounds of the harbor — lapping waves, creaking hulls, distant gulls — filter through the rusted bars. The grate is solid despite its age, too strong to break through. A cold sea breeze pushes in, carrying the smell of brine and open air.`,
        area: 'Arindale Sewer',
        terrain: 'underground',
        darkness_level: -120,
      },
      {
        tag: 'sewer_north_1',
        name: 'Drainage Tunnel',
        description: desc('sewer_north_1'),
        area: 'Arindale Sewer',
        terrain: 'underground',
        darkness_level: -120,
      },
      {
        tag: 'sewer_north_2',
        name: 'Drainage Passage',
        description: desc('sewer_north_2'),
        area: 'Arindale Sewer',
        terrain: 'underground',
        darkness_level: -120,
      },
      {
        tag: 'sewer_north_3',
        name: 'Damp Passage',
        description: desc('sewer_north_3'),
        area: 'Arindale Sewer',
        terrain: 'underground',
        darkness_level: -120,
      },
      {
        tag: 'sewer_north_4',
        name: 'Dark Passage',
        description: desc('sewer_north_4'),
        area: 'Arindale Sewer',
        terrain: 'underground',
        darkness_level: -120,
      },
      {
        tag: 'sewer_north_5',
        name: 'Brick Tunnel',
        description: desc('sewer_north_5'),
        area: 'Arindale Sewer',
        terrain: 'underground',
        darkness_level: -120,
      },
      {
        tag: 'sewer_north_hub',
        name: 'Harbor Drainage Junction',
        description: `A large junction chamber beneath the harbor district. Seawater seeps steadily through the walls, mixing with the sewer flow and filling the air with the smell of brine and rot. A vertical shaft leads up to a manhole on the street far above. Tunnels branch in all directions, their walls glistening with moisture in the dim light.`,
        area: 'Arindale Sewer',
        terrain: 'underground',
        darkness_level: -120,
      },
      {
        tag: 'sewer_north_6',
        name: 'Harbor Drainage',
        description: desc('sewer_north_6'),
        area: 'Arindale Sewer',
        terrain: 'underground',
        darkness_level: -120,
      },
      {
        tag: 'sewer_north_7',
        name: 'Waterlogged Corridor',
        description: desc('sewer_north_7'),
        area: 'Arindale Sewer',
        terrain: 'underground',
        darkness_level: -120,
      },
      {
        tag: 'sewer_north_8',
        name: 'Side Passage',
        description: desc('sewer_north_8'),
        area: 'Arindale Sewer',
        terrain: 'underground',
        darkness_level: -120,
      },
      {
        tag: 'sewer_north_9',
        name: 'Damp Tunnel',
        description: desc('sewer_north_9'),
        area: 'Arindale Sewer',
        terrain: 'underground',
        darkness_level: -120,
      },
      {
        tag: 'sewer_north_10',
        name: 'Damp Passage',
        description: desc('sewer_north_10'),
        area: 'Arindale Sewer',
        terrain: 'underground',
        darkness_level: -120,
      },
      {
        tag: 'sewer_north_11',
        name: 'Drainage Passage',
        description: desc('sewer_north_11'),
        area: 'Arindale Sewer',
        terrain: 'underground',
        darkness_level: -120,
      },
      {
        tag: 'sewer_north_12',
        name: 'Drainage Tunnel',
        description: desc('sewer_north_12'),
        area: 'Arindale Sewer',
        terrain: 'underground',
        darkness_level: -120,
      },
      {
        tag: 'sewer_north_13',
        name: 'Harbor Passage',
        description: desc('sewer_north_13'),
        area: 'Arindale Sewer',
        terrain: 'underground',
        darkness_level: -120,
      },
      {
        tag: 'sewer_north_14',
        name: 'Damp Tunnel',
        description: desc('sewer_north_14'),
        area: 'Arindale Sewer',
        terrain: 'underground',
        darkness_level: -120,
      },
      {
        tag: 'sewer_north_15',
        name: 'Side Passage',
        description: desc('sewer_north_15'),
        area: 'Arindale Sewer',
        terrain: 'underground',
        darkness_level: -120,
      },
      {
        tag: 'sewer_north_16',
        name: 'Waterlogged Corridor',
        description: desc('sewer_north_16'),
        area: 'Arindale Sewer',
        terrain: 'underground',
        darkness_level: -120,
      },
      {
        tag: 'sewer_north_17',
        name: 'Harbor Drainage',
        description: desc('sewer_north_17'),
        area: 'Arindale Sewer',
        terrain: 'underground',
        darkness_level: -120,
      },
      {
        tag: 'sewer_north_18',
        name: 'Brick Tunnel',
        description: desc('sewer_north_18'),
        area: 'Arindale Sewer',
        terrain: 'underground',
        darkness_level: -120,
      },
      {
        tag: 'sewer_north_19',
        name: 'Dark Passage',
        description: desc('sewer_north_19'),
        area: 'Arindale Sewer',
        terrain: 'underground',
        darkness_level: -120,
      },
      {
        tag: 'sewer_north_20',
        name: 'Drainage Passage',
        description: desc('sewer_north_20'),
        area: 'Arindale Sewer',
        terrain: 'underground',
        darkness_level: -120,
      },
      {
        tag: 'sewer_flooded_1',
        name: 'Flooded Tunnel',
        description: `Water rises to knee height in this section of tunnel. The flooding has turned the passage into a wading channel, the current sluggish but persistent. Debris floats on the surface — scraps of wood, matted refuse, and less identifiable things. The walls are slimy above the waterline.`,
        area: 'Arindale Sewer',
        terrain: 'underground',
        darkness_level: -120,
      },
      {
        tag: 'sewer_north_21',
        name: 'Drainage Tunnel',
        description: desc('sewer_north_21'),
        area: 'Arindale Sewer',
        terrain: 'underground',
        darkness_level: -120,
      },
      {
        tag: 'sewer_north_22',
        name: 'Harbor Passage',
        description: desc('sewer_north_22'),
        area: 'Arindale Sewer',
        terrain: 'underground',
        darkness_level: -120,
      },
      {
        tag: 'sewer_entrance_sanctum',
        name: 'Incense-Stained Passage',
        description: `The tunnel walls here bear strange carved symbols — angular, deliberate marks that are clearly not mason's work. The faint smell of incense hangs in the still air, incongruous in the sewer's filth. A dark opening in the wall has been framed with fitted stones, creating an archway where the rough tunnel meets something older and more purposeful beyond. Scorch marks from candles or torches blacken the stone around the entrance.`,
        area: 'Arindale Sewer',
        terrain: 'underground',
        darkness_level: -120,
      },
      {
        tag: 'sewer_north_23',
        name: 'Damp Tunnel',
        description: desc('sewer_north_23'),
        area: 'Arindale Sewer',
        terrain: 'underground',
        darkness_level: -120,
      },
      {
        tag: 'sewer_north_24',
        name: 'Side Passage',
        description: desc('sewer_north_24'),
        area: 'Arindale Sewer',
        terrain: 'underground',
        darkness_level: -120,
      },
      {
        tag: 'sewer_north_25',
        name: 'Waterlogged Corridor',
        description: desc('sewer_north_25'),
        area: 'Arindale Sewer',
        terrain: 'underground',
        darkness_level: -120,
      },
      {
        tag: 'sewer_north_26',
        name: 'Harbor Drainage',
        description: desc('sewer_north_26'),
        area: 'Arindale Sewer',
        terrain: 'underground',
        darkness_level: -120,
      },
      {
        tag: 'sewer_north_27',
        name: 'Brick Tunnel',
        description: desc('sewer_north_27'),
        area: 'Arindale Sewer',
        terrain: 'underground',
        darkness_level: -120,
      },
      {
        tag: 'sewer_north_28',
        name: 'Dark Passage',
        description: desc('sewer_north_28'),
        area: 'Arindale Sewer',
        terrain: 'underground',
        darkness_level: -120,
      },
      {
        tag: 'sewer_north_29',
        name: 'Damp Passage',
        description: desc('sewer_north_29'),
        area: 'Arindale Sewer',
        terrain: 'underground',
        darkness_level: -120,
      },
      {
        tag: 'sewer_north_30',
        name: 'Drainage Tunnel',
        description: desc('sewer_north_30'),
        area: 'Arindale Sewer',
        terrain: 'underground',
        darkness_level: -120,
      },
      {
        tag: 'sewer_north_31',
        name: 'Harbor Passage',
        description: desc('sewer_north_31'),
        area: 'Arindale Sewer',
        terrain: 'underground',
        darkness_level: -120,
      },
      {
        tag: 'sewer_north_32',
        name: 'Damp Tunnel',
        description: desc('sewer_north_32'),
        area: 'Arindale Sewer',
        terrain: 'underground',
        darkness_level: -120,
      },
      {
        tag: 'sewer_north_33',
        name: 'Side Passage',
        description: desc('sewer_north_33'),
        area: 'Arindale Sewer',
        terrain: 'underground',
        darkness_level: -120,
      },
      {
        tag: 'sewer_north_34',
        name: 'Waterlogged Corridor',
        description: desc('sewer_north_34'),
        area: 'Arindale Sewer',
        terrain: 'underground',
        darkness_level: -120,
      },
      {
        tag: 'sewer_north_35',
        name: 'Harbor Drainage',
        description: desc('sewer_north_35'),
        area: 'Arindale Sewer',
        terrain: 'underground',
        darkness_level: -120,
      },
      {
        tag: 'sewer_flooded_2',
        name: 'Flooded Passage',
        description: `The flooding deepens here, dark water reaching waist-height in the lower sections. The tunnel slopes downward, and the current grows stronger, pulling at anything in its path. The walls are coated in thick green algae up to the ceiling. The air is heavy and foul.`,
        area: 'Arindale Sewer',
        terrain: 'underground',
        darkness_level: -120,
      },
      {
        tag: 'sewer_flooded_3',
        name: 'Damp Passage',
        description: flDesc('sewer_flooded_3'),
        area: 'Arindale Sewer',
        terrain: 'underground',
        darkness_level: -120,
      },
      {
        tag: 'sewer_north_36',
        name: 'Brick Tunnel',
        description: desc('sewer_north_36'),
        area: 'Arindale Sewer',
        terrain: 'underground',
        darkness_level: -120,
      },
      {
        tag: 'sewer_north_37',
        name: 'Dark Passage',
        description: desc('sewer_north_37'),
        area: 'Arindale Sewer',
        terrain: 'underground',
        darkness_level: -120,
      },
      {
        tag: 'sewer_north_38',
        name: 'Damp Passage',
        description: desc('sewer_north_38'),
        area: 'Arindale Sewer',
        terrain: 'underground',
        darkness_level: -120,
      },
      {
        tag: 'sewer_north_39',
        name: 'Drainage Passage',
        description: desc('sewer_north_39'),
        area: 'Arindale Sewer',
        terrain: 'underground',
        darkness_level: -120,
      },
      {
        tag: 'sewer_north_40',
        name: 'Harbor Passage',
        description: desc('sewer_north_40'),
        area: 'Arindale Sewer',
        terrain: 'underground',
        darkness_level: -120,
      },
      {
        tag: 'sewer_north_41',
        name: 'Damp Tunnel',
        description: desc('sewer_north_41'),
        area: 'Arindale Sewer',
        terrain: 'underground',
        darkness_level: -120,
      },
      {
        tag: 'sewer_north_42',
        name: 'Side Passage',
        description: desc('sewer_north_42'),
        area: 'Arindale Sewer',
        terrain: 'underground',
        darkness_level: -120,
      },
      {
        tag: 'sewer_north_43',
        name: 'Waterlogged Corridor',
        description: desc('sewer_north_43'),
        area: 'Arindale Sewer',
        terrain: 'underground',
        darkness_level: -120,
      },
      {
        tag: 'sewer_north_44',
        name: 'Harbor Drainage',
        description: desc('sewer_north_44'),
        area: 'Arindale Sewer',
        terrain: 'underground',
        darkness_level: -120,
      },
      {
        tag: 'sewer_north_45',
        name: 'Brick Tunnel',
        description: desc('sewer_north_45'),
        area: 'Arindale Sewer',
        terrain: 'underground',
        darkness_level: -120,
      },
      {
        tag: 'sewer_north_46',
        name: 'Dark Passage',
        description: desc('sewer_north_46'),
        area: 'Arindale Sewer',
        terrain: 'underground',
        darkness_level: -120,
      },
      {
        tag: 'sewer_north_47',
        name: 'Damp Passage',
        description: desc('sewer_north_47'),
        area: 'Arindale Sewer',
        terrain: 'underground',
        darkness_level: -120,
      },
      {
        tag: 'sewer_north_48',
        name: 'Drainage Passage',
        description: desc('sewer_north_48'),
        area: 'Arindale Sewer',
        terrain: 'underground',
        darkness_level: -120,
      },
      {
        tag: 'sewer_north_49',
        name: 'Drainage Tunnel',
        description: desc('sewer_north_49'),
        area: 'Arindale Sewer',
        terrain: 'underground',
        darkness_level: -120,
      },
      {
        tag: 'sewer_north_50',
        name: 'Damp Tunnel',
        description: desc('sewer_north_50'),
        area: 'Arindale Sewer',
        terrain: 'underground',
        darkness_level: -120,
      },
      {
        tag: 'sewer_flooded_4',
        name: 'Dark Passage',
        description: flDesc('sewer_flooded_4'),
        area: 'Arindale Sewer',
        terrain: 'underground',
        darkness_level: -120,
      },
      {
        tag: 'sewer_flooded_5',
        name: 'Brick Tunnel',
        description: flDesc('sewer_flooded_5'),
        area: 'Arindale Sewer',
        terrain: 'underground',
        darkness_level: -120,
      },
      {
        tag: 'sewer_north_51',
        name: 'Side Passage',
        description: desc('sewer_north_51'),
        area: 'Arindale Sewer',
        terrain: 'underground',
        darkness_level: -120,
      },
      {
        tag: 'sewer_north_52',
        name: 'Waterlogged Corridor',
        description: desc('sewer_north_52'),
        area: 'Arindale Sewer',
        terrain: 'underground',
        darkness_level: -120,
      },
      {
        tag: 'sewer_north_53',
        name: 'Harbor Drainage',
        description: desc('sewer_north_53'),
        area: 'Arindale Sewer',
        terrain: 'underground',
        darkness_level: -120,
      },
      {
        tag: 'sewer_north_54',
        name: 'Brick Tunnel',
        description: desc('sewer_north_54'),
        area: 'Arindale Sewer',
        terrain: 'underground',
        darkness_level: -120,
      },
      {
        tag: 'sewer_north_55',
        name: 'Dark Passage',
        description: desc('sewer_north_55'),
        area: 'Arindale Sewer',
        terrain: 'underground',
        darkness_level: -120,
      },
      {
        tag: 'sewer_north_56',
        name: 'Damp Passage',
        description: desc('sewer_north_56'),
        area: 'Arindale Sewer',
        terrain: 'underground',
        darkness_level: -120,
      },
      {
        tag: 'sewer_north_57',
        name: 'Drainage Passage',
        description: desc('sewer_north_57'),
        area: 'Arindale Sewer',
        terrain: 'underground',
        darkness_level: -120,
      },
      {
        tag: 'sewer_north_58',
        name: 'Drainage Tunnel',
        description: desc('sewer_north_58'),
        area: 'Arindale Sewer',
        terrain: 'underground',
        darkness_level: -120,
      },
      {
        tag: 'sewer_north_59',
        name: 'Harbor Passage',
        description: desc('sewer_north_59'),
        area: 'Arindale Sewer',
        terrain: 'underground',
        darkness_level: -120,
      },
      {
        tag: 'sewer_north_60',
        name: 'Side Passage',
        description: desc('sewer_north_60'),
        area: 'Arindale Sewer',
        terrain: 'underground',
        darkness_level: -120,
      },
      {
        tag: 'sewer_north_61',
        name: 'Waterlogged Corridor',
        description: desc('sewer_north_61'),
        area: 'Arindale Sewer',
        terrain: 'underground',
        darkness_level: -120,
      },
      {
        tag: 'sewer_north_62',
        name: 'Harbor Drainage',
        description: desc('sewer_north_62'),
        area: 'Arindale Sewer',
        terrain: 'underground',
        darkness_level: -120,
      },
      {
        tag: 'sewer_north_63',
        name: 'Brick Tunnel',
        description: desc('sewer_north_63'),
        area: 'Arindale Sewer',
        terrain: 'underground',
        darkness_level: -120,
      },
      {
        tag: 'sewer_north_64',
        name: 'Dark Passage',
        description: desc('sewer_north_64'),
        area: 'Arindale Sewer',
        terrain: 'underground',
        darkness_level: -120,
      },
      {
        tag: 'sewer_north_65',
        name: 'Damp Passage',
        description: desc('sewer_north_65'),
        area: 'Arindale Sewer',
        terrain: 'underground',
        darkness_level: -120,
      },
      {
        tag: 'sewer_north_66',
        name: 'Drainage Passage',
        description: desc('sewer_north_66'),
        area: 'Arindale Sewer',
        terrain: 'underground',
        darkness_level: -120,
      },
      {
        tag: 'sewer_north_67',
        name: 'Drainage Tunnel',
        description: desc('sewer_north_67'),
        area: 'Arindale Sewer',
        terrain: 'underground',
        darkness_level: -120,
      },
      {
        tag: 'sewer_north_68',
        name: 'Harbor Passage',
        description: desc('sewer_north_68'),
        area: 'Arindale Sewer',
        terrain: 'underground',
        darkness_level: -120,
      },
      {
        tag: 'sewer_north_69',
        name: 'Damp Tunnel',
        description: desc('sewer_north_69'),
        area: 'Arindale Sewer',
        terrain: 'underground',
        darkness_level: -120,
      },
      {
        tag: 'sewer_north_70',
        name: 'Waterlogged Corridor',
        description: desc('sewer_north_70'),
        area: 'Arindale Sewer',
        terrain: 'underground',
        darkness_level: -120,
      },
      {
        tag: 'sewer_north_71',
        name: 'Harbor Drainage',
        description: desc('sewer_north_71'),
        area: 'Arindale Sewer',
        terrain: 'underground',
        darkness_level: -120,
      },
      {
        tag: 'sewer_north_72',
        name: 'Brick Tunnel',
        description: desc('sewer_north_72'),
        area: 'Arindale Sewer',
        terrain: 'underground',
        darkness_level: -120,
      },
      {
        tag: 'sewer_north_73',
        name: 'Dark Passage',
        description: desc('sewer_north_73'),
        area: 'Arindale Sewer',
        terrain: 'underground',
        darkness_level: -120,
      },
      {
        tag: 'sewer_north_74',
        name: 'Damp Passage',
        description: desc('sewer_north_74'),
        area: 'Arindale Sewer',
        terrain: 'underground',
        darkness_level: -120,
      },
      {
        tag: 'sewer_north_75',
        name: 'Drainage Passage',
        description: desc('sewer_north_75'),
        area: 'Arindale Sewer',
        terrain: 'underground',
        darkness_level: -120,
      },
      {
        tag: 'sewer_north_76',
        name: 'Drainage Tunnel',
        description: desc('sewer_north_76'),
        area: 'Arindale Sewer',
        terrain: 'underground',
        darkness_level: -120,
      },
      {
        tag: 'sewer_north_77',
        name: 'Harbor Passage',
        description: desc('sewer_north_77'),
        area: 'Arindale Sewer',
        terrain: 'underground',
        darkness_level: -120,
      },
    ],

    exits: [
      { fromTag: 'sewer_north_hub', toTag: 'int_0_2', direction: 'up' },
      { fromTag: 'int_0_2', toTag: 'sewer_north_hub', direction: 'down' },
      { fromTag: 'sewer_north_1', toTag: 'sewer_north_2', direction: 'east' },
      { fromTag: 'sewer_north_2', toTag: 'sewer_north_1', direction: 'west' },
      { fromTag: 'sewer_north_2', toTag: 'sewer_north_3', direction: 'east' },
      { fromTag: 'sewer_north_3', toTag: 'sewer_north_2', direction: 'west' },
      { fromTag: 'sewer_north_3', toTag: 'sewer_north_4', direction: 'east' },
      { fromTag: 'sewer_north_4', toTag: 'sewer_north_3', direction: 'west' },
      { fromTag: 'sewer_north_4', toTag: 'sewer_north_5', direction: 'east' },
      { fromTag: 'sewer_north_5', toTag: 'sewer_north_4', direction: 'west' },
      { fromTag: 'sewer_north_5', toTag: 'sewer_north_hub', direction: 'east' },
      { fromTag: 'sewer_north_hub', toTag: 'sewer_north_5', direction: 'west' },
      { fromTag: 'sewer_north_hub', toTag: 'sewer_north_6', direction: 'east' },
      { fromTag: 'sewer_north_6', toTag: 'sewer_north_hub', direction: 'west' },
      { fromTag: 'sewer_north_6', toTag: 'sewer_north_7', direction: 'east' },
      { fromTag: 'sewer_north_7', toTag: 'sewer_north_6', direction: 'west' },
      { fromTag: 'sewer_north_7', toTag: 'sewer_north_8', direction: 'east' },
      { fromTag: 'sewer_north_8', toTag: 'sewer_north_7', direction: 'west' },
      { fromTag: 'sewer_north_8', toTag: 'sewer_north_9', direction: 'east' },
      { fromTag: 'sewer_north_9', toTag: 'sewer_north_8', direction: 'west' },
      { fromTag: 'sewer_north_9', toTag: 'sewer_north_10', direction: 'east' },
      { fromTag: 'sewer_north_10', toTag: 'sewer_north_9', direction: 'west' },
      { fromTag: 'sewer_north_10', toTag: 'sewer_north_11', direction: 'east' },
      { fromTag: 'sewer_north_11', toTag: 'sewer_north_10', direction: 'west' },
      { fromTag: 'sewer_north_11', toTag: 'sewer_north_12', direction: 'east' },
      { fromTag: 'sewer_north_12', toTag: 'sewer_north_11', direction: 'west' },
      { fromTag: 'sewer_north_12', toTag: 'sewer_north_13', direction: 'east' },
      { fromTag: 'sewer_north_13', toTag: 'sewer_north_12', direction: 'west' },
      { fromTag: 'sewer_north_13', toTag: 'sewer_north_14', direction: 'east' },
      { fromTag: 'sewer_north_14', toTag: 'sewer_north_13', direction: 'west' },
      { fromTag: 'sewer_north_14', toTag: 'sewer_north_15', direction: 'east' },
      { fromTag: 'sewer_north_15', toTag: 'sewer_north_14', direction: 'west' },
      { fromTag: 'sewer_north_15', toTag: 'sewer_north_16', direction: 'east' },
      { fromTag: 'sewer_north_16', toTag: 'sewer_north_15', direction: 'west' },
      { fromTag: 'sewer_north_16', toTag: 'sewer_north_17', direction: 'east' },
      { fromTag: 'sewer_north_17', toTag: 'sewer_north_16', direction: 'west' },
      { fromTag: 'sewer_north_19', toTag: 'sewer_north_20', direction: 'east' },
      { fromTag: 'sewer_north_20', toTag: 'sewer_north_19', direction: 'west' },
      { fromTag: 'sewer_flooded_1', toTag: 'sewer_north_21', direction: 'east' },
      { fromTag: 'sewer_north_21', toTag: 'sewer_flooded_1', direction: 'west' },
      { fromTag: 'sewer_entrance_sanctum', toTag: 'sewer_north_23', direction: 'east' },
      { fromTag: 'sewer_north_23', toTag: 'sewer_entrance_sanctum', direction: 'west' },
      { fromTag: 'sewer_north_23', toTag: 'sewer_north_24', direction: 'east' },
      { fromTag: 'sewer_north_24', toTag: 'sewer_north_23', direction: 'west' },
      { fromTag: 'sewer_north_30', toTag: 'sewer_north_31', direction: 'east' },
      { fromTag: 'sewer_north_31', toTag: 'sewer_north_30', direction: 'west' },
      { fromTag: 'sewer_north_32', toTag: 'sewer_north_33', direction: 'east' },
      { fromTag: 'sewer_north_33', toTag: 'sewer_north_32', direction: 'west' },
      { fromTag: 'sewer_flooded_2', toTag: 'sewer_flooded_3', direction: 'east' },
      { fromTag: 'sewer_flooded_3', toTag: 'sewer_flooded_2', direction: 'west' },
      { fromTag: 'sewer_north_36', toTag: 'sewer_north_37', direction: 'east' },
      { fromTag: 'sewer_north_37', toTag: 'sewer_north_36', direction: 'west' },
      { fromTag: 'sewer_north_37', toTag: 'sewer_north_38', direction: 'east' },
      { fromTag: 'sewer_north_38', toTag: 'sewer_north_37', direction: 'west' },
      { fromTag: 'sewer_north_38', toTag: 'sewer_north_39', direction: 'east' },
      { fromTag: 'sewer_north_39', toTag: 'sewer_north_38', direction: 'west' },
      { fromTag: 'sewer_north_39', toTag: 'sewer_north_40', direction: 'east' },
      { fromTag: 'sewer_north_40', toTag: 'sewer_north_39', direction: 'west' },
      { fromTag: 'sewer_north_40', toTag: 'sewer_north_41', direction: 'east' },
      { fromTag: 'sewer_north_41', toTag: 'sewer_north_40', direction: 'west' },
      { fromTag: 'sewer_north_41', toTag: 'sewer_north_42', direction: 'east' },
      { fromTag: 'sewer_north_42', toTag: 'sewer_north_41', direction: 'west' },
      { fromTag: 'sewer_north_42', toTag: 'sewer_north_43', direction: 'east' },
      { fromTag: 'sewer_north_43', toTag: 'sewer_north_42', direction: 'west' },
      { fromTag: 'sewer_north_43', toTag: 'sewer_north_44', direction: 'east' },
      { fromTag: 'sewer_north_44', toTag: 'sewer_north_43', direction: 'west' },
      { fromTag: 'sewer_north_44', toTag: 'sewer_north_45', direction: 'east' },
      { fromTag: 'sewer_north_45', toTag: 'sewer_north_44', direction: 'west' },
      { fromTag: 'sewer_north_47', toTag: 'sewer_north_48', direction: 'east' },
      { fromTag: 'sewer_north_48', toTag: 'sewer_north_47', direction: 'west' },
      { fromTag: 'sewer_flooded_4', toTag: 'sewer_flooded_5', direction: 'east' },
      { fromTag: 'sewer_flooded_5', toTag: 'sewer_flooded_4', direction: 'west' },
      { fromTag: 'sewer_north_62', toTag: 'sewer_north_63', direction: 'east' },
      { fromTag: 'sewer_north_63', toTag: 'sewer_north_62', direction: 'west' },
      { fromTag: 'sewer_north_65', toTag: 'sewer_north_66', direction: 'east' },
      { fromTag: 'sewer_north_66', toTag: 'sewer_north_65', direction: 'west' },
      { fromTag: 'sewer_north_66', toTag: 'sewer_north_67', direction: 'east' },
      { fromTag: 'sewer_north_67', toTag: 'sewer_north_66', direction: 'west' },
      { fromTag: 'sewer_north_67', toTag: 'sewer_north_68', direction: 'east' },
      { fromTag: 'sewer_north_68', toTag: 'sewer_north_67', direction: 'west' },
      { fromTag: 'sewer_north_68', toTag: 'sewer_north_69', direction: 'east' },
      { fromTag: 'sewer_north_69', toTag: 'sewer_north_68', direction: 'west' },
      { fromTag: 'sewer_north_70', toTag: 'sewer_north_71', direction: 'east' },
      { fromTag: 'sewer_north_71', toTag: 'sewer_north_70', direction: 'west' },
      { fromTag: 'sewer_north_71', toTag: 'sewer_north_72', direction: 'east' },
      { fromTag: 'sewer_north_72', toTag: 'sewer_north_71', direction: 'west' },
      { fromTag: 'sewer_north_72', toTag: 'sewer_north_73', direction: 'east' },
      { fromTag: 'sewer_north_73', toTag: 'sewer_north_72', direction: 'west' },
      { fromTag: 'sewer_north_73', toTag: 'sewer_north_74', direction: 'east' },
      { fromTag: 'sewer_north_74', toTag: 'sewer_north_73', direction: 'west' },
      { fromTag: 'sewer_north_75', toTag: 'sewer_north_76', direction: 'east' },
      { fromTag: 'sewer_north_76', toTag: 'sewer_north_75', direction: 'west' },
      { fromTag: 'sewer_north_76', toTag: 'sewer_north_77', direction: 'east' },
      { fromTag: 'sewer_north_77', toTag: 'sewer_north_76', direction: 'west' },
      { fromTag: 'sewer_drain_outflow', toTag: 'sewer_north_2', direction: 'south' },
      { fromTag: 'sewer_north_2', toTag: 'sewer_drain_outflow', direction: 'north' },
      { fromTag: 'sewer_north_1', toTag: 'sewer_north_18', direction: 'south' },
      { fromTag: 'sewer_north_18', toTag: 'sewer_north_1', direction: 'north' },
      { fromTag: 'sewer_north_3', toTag: 'sewer_north_20', direction: 'south' },
      { fromTag: 'sewer_north_20', toTag: 'sewer_north_3', direction: 'north' },
      { fromTag: 'sewer_north_5', toTag: 'sewer_north_21', direction: 'south' },
      { fromTag: 'sewer_north_21', toTag: 'sewer_north_5', direction: 'north' },
      { fromTag: 'sewer_north_hub', toTag: 'sewer_north_22', direction: 'south' },
      { fromTag: 'sewer_north_22', toTag: 'sewer_north_hub', direction: 'north' },
      { fromTag: 'sewer_north_8', toTag: 'sewer_north_24', direction: 'south' },
      { fromTag: 'sewer_north_24', toTag: 'sewer_north_8', direction: 'north' },
      { fromTag: 'sewer_north_9', toTag: 'sewer_north_25', direction: 'south' },
      { fromTag: 'sewer_north_25', toTag: 'sewer_north_9', direction: 'north' },
      { fromTag: 'sewer_north_10', toTag: 'sewer_north_26', direction: 'south' },
      { fromTag: 'sewer_north_26', toTag: 'sewer_north_10', direction: 'north' },
      { fromTag: 'sewer_north_11', toTag: 'sewer_north_27', direction: 'south' },
      { fromTag: 'sewer_north_27', toTag: 'sewer_north_11', direction: 'north' },
      { fromTag: 'sewer_north_12', toTag: 'sewer_north_28', direction: 'south' },
      { fromTag: 'sewer_north_28', toTag: 'sewer_north_12', direction: 'north' },
      { fromTag: 'sewer_north_13', toTag: 'sewer_north_29', direction: 'south' },
      { fromTag: 'sewer_north_29', toTag: 'sewer_north_13', direction: 'north' },
      { fromTag: 'sewer_north_15', toTag: 'sewer_north_31', direction: 'south' },
      { fromTag: 'sewer_north_31', toTag: 'sewer_north_15', direction: 'north' },
      { fromTag: 'sewer_north_17', toTag: 'sewer_north_33', direction: 'south' },
      { fromTag: 'sewer_north_33', toTag: 'sewer_north_17', direction: 'north' },
      { fromTag: 'sewer_north_18', toTag: 'sewer_north_34', direction: 'south' },
      { fromTag: 'sewer_north_34', toTag: 'sewer_north_18', direction: 'north' },
      { fromTag: 'sewer_north_19', toTag: 'sewer_north_35', direction: 'south' },
      { fromTag: 'sewer_north_35', toTag: 'sewer_north_19', direction: 'north' },
      { fromTag: 'sewer_flooded_1', toTag: 'sewer_flooded_3', direction: 'south' },
      { fromTag: 'sewer_flooded_3', toTag: 'sewer_flooded_1', direction: 'north' },
      { fromTag: 'sewer_north_21', toTag: 'sewer_north_36', direction: 'south' },
      { fromTag: 'sewer_north_36', toTag: 'sewer_north_21', direction: 'north' },
      { fromTag: 'sewer_north_22', toTag: 'sewer_north_37', direction: 'south' },
      { fromTag: 'sewer_north_37', toTag: 'sewer_north_22', direction: 'north' },
      { fromTag: 'sewer_north_24', toTag: 'sewer_north_40', direction: 'south' },
      { fromTag: 'sewer_north_40', toTag: 'sewer_north_24', direction: 'north' },
      { fromTag: 'sewer_north_25', toTag: 'sewer_north_41', direction: 'south' },
      { fromTag: 'sewer_north_41', toTag: 'sewer_north_25', direction: 'north' },
      { fromTag: 'sewer_north_26', toTag: 'sewer_north_42', direction: 'south' },
      { fromTag: 'sewer_north_42', toTag: 'sewer_north_26', direction: 'north' },
      { fromTag: 'sewer_north_27', toTag: 'sewer_north_43', direction: 'south' },
      { fromTag: 'sewer_north_43', toTag: 'sewer_north_27', direction: 'north' },
      { fromTag: 'sewer_north_28', toTag: 'sewer_north_44', direction: 'south' },
      { fromTag: 'sewer_north_44', toTag: 'sewer_north_28', direction: 'north' },
      { fromTag: 'sewer_north_29', toTag: 'sewer_north_45', direction: 'south' },
      { fromTag: 'sewer_north_45', toTag: 'sewer_north_29', direction: 'north' },
      { fromTag: 'sewer_north_30', toTag: 'sewer_north_46', direction: 'south' },
      { fromTag: 'sewer_north_46', toTag: 'sewer_north_30', direction: 'north' },
      { fromTag: 'sewer_north_32', toTag: 'sewer_north_48', direction: 'south' },
      { fromTag: 'sewer_north_48', toTag: 'sewer_north_32', direction: 'north' },
      { fromTag: 'sewer_north_34', toTag: 'sewer_north_49', direction: 'south' },
      { fromTag: 'sewer_north_49', toTag: 'sewer_north_34', direction: 'north' },
      { fromTag: 'sewer_north_35', toTag: 'sewer_north_50', direction: 'south' },
      { fromTag: 'sewer_north_50', toTag: 'sewer_north_35', direction: 'north' },
      { fromTag: 'sewer_flooded_3', toTag: 'sewer_flooded_5', direction: 'south' },
      { fromTag: 'sewer_flooded_5', toTag: 'sewer_flooded_3', direction: 'north' },
      { fromTag: 'sewer_north_36', toTag: 'sewer_north_51', direction: 'south' },
      { fromTag: 'sewer_north_51', toTag: 'sewer_north_36', direction: 'north' },
      { fromTag: 'sewer_north_37', toTag: 'sewer_north_52', direction: 'south' },
      { fromTag: 'sewer_north_52', toTag: 'sewer_north_37', direction: 'north' },
      { fromTag: 'sewer_north_38', toTag: 'sewer_north_53', direction: 'south' },
      { fromTag: 'sewer_north_53', toTag: 'sewer_north_38', direction: 'north' },
      { fromTag: 'sewer_north_39', toTag: 'sewer_north_54', direction: 'south' },
      { fromTag: 'sewer_north_54', toTag: 'sewer_north_39', direction: 'north' },
      { fromTag: 'sewer_north_40', toTag: 'sewer_north_55', direction: 'south' },
      { fromTag: 'sewer_north_55', toTag: 'sewer_north_40', direction: 'north' },
      { fromTag: 'sewer_north_41', toTag: 'sewer_north_56', direction: 'south' },
      { fromTag: 'sewer_north_56', toTag: 'sewer_north_41', direction: 'north' },
      { fromTag: 'sewer_north_42', toTag: 'sewer_north_57', direction: 'south' },
      { fromTag: 'sewer_north_57', toTag: 'sewer_north_42', direction: 'north' },
      { fromTag: 'sewer_north_43', toTag: 'sewer_north_58', direction: 'south' },
      { fromTag: 'sewer_north_58', toTag: 'sewer_north_43', direction: 'north' },
      { fromTag: 'sewer_north_45', toTag: 'sewer_north_59', direction: 'south' },
      { fromTag: 'sewer_north_59', toTag: 'sewer_north_45', direction: 'north' },
      { fromTag: 'sewer_north_46', toTag: 'sewer_north_60', direction: 'south' },
      { fromTag: 'sewer_north_60', toTag: 'sewer_north_46', direction: 'north' },
      { fromTag: 'sewer_north_47', toTag: 'sewer_north_61', direction: 'south' },
      { fromTag: 'sewer_north_61', toTag: 'sewer_north_47', direction: 'north' },
      { fromTag: 'sewer_north_49', toTag: 'sewer_north_62', direction: 'south' },
      { fromTag: 'sewer_north_62', toTag: 'sewer_north_49', direction: 'north' },
      { fromTag: 'sewer_north_50', toTag: 'sewer_north_63', direction: 'south' },
      { fromTag: 'sewer_north_63', toTag: 'sewer_north_50', direction: 'north' },
      { fromTag: 'sewer_flooded_4', toTag: 'sewer_north_64', direction: 'south' },
      { fromTag: 'sewer_north_64', toTag: 'sewer_flooded_4', direction: 'north' },
      { fromTag: 'sewer_north_51', toTag: 'sewer_north_66', direction: 'south' },
      { fromTag: 'sewer_north_66', toTag: 'sewer_north_51', direction: 'north' },
      { fromTag: 'sewer_north_52', toTag: 'sewer_north_67', direction: 'south' },
      { fromTag: 'sewer_north_67', toTag: 'sewer_north_52', direction: 'north' },
      { fromTag: 'sewer_north_53', toTag: 'sewer_north_68', direction: 'south' },
      { fromTag: 'sewer_north_68', toTag: 'sewer_north_53', direction: 'north' },
      { fromTag: 'sewer_north_54', toTag: 'sewer_north_69', direction: 'south' },
      { fromTag: 'sewer_north_69', toTag: 'sewer_north_54', direction: 'north' },
      { fromTag: 'sewer_north_55', toTag: 'sewer_north_70', direction: 'south' },
      { fromTag: 'sewer_north_70', toTag: 'sewer_north_55', direction: 'north' },
      { fromTag: 'sewer_north_56', toTag: 'sewer_north_71', direction: 'south' },
      { fromTag: 'sewer_north_71', toTag: 'sewer_north_56', direction: 'north' },
      { fromTag: 'sewer_north_57', toTag: 'sewer_north_72', direction: 'south' },
      { fromTag: 'sewer_north_72', toTag: 'sewer_north_57', direction: 'north' },
      { fromTag: 'sewer_north_58', toTag: 'sewer_north_73', direction: 'south' },
      { fromTag: 'sewer_north_73', toTag: 'sewer_north_58', direction: 'north' },
      { fromTag: 'sewer_north_59', toTag: 'sewer_north_75', direction: 'south' },
      { fromTag: 'sewer_north_75', toTag: 'sewer_north_59', direction: 'north' },
      { fromTag: 'sewer_north_60', toTag: 'sewer_north_76', direction: 'south' },
      { fromTag: 'sewer_north_76', toTag: 'sewer_north_60', direction: 'north' },
      { fromTag: 'sewer_north_61', toTag: 'sewer_north_77', direction: 'south' },
      { fromTag: 'sewer_north_77', toTag: 'sewer_north_61', direction: 'north' },
    ],

    doors: [
      {
        name: 'manhole',
        doorType: 'triggered_passageway',
        entryTag: 'int_0_2',
        entryDirection: 'down',
        defaultState: 'closed',
        autoResetSeconds: 30,
        isHidden: true,
        triggerText: 'go manhole',
        passageMessageSelf: 'You lift the heavy iron grate and climb down into the sewer.',
        passageMessageRoom: '{player} lifts a manhole grate and climbs down into the darkness below.',
      }
    ],
  };
}
